### ISSUE TITLE
你们自动上传符号表功能都正常吗？

### ISSUE THREAD

**Issue by pcjbird** [BuglyDevTeam/Bugly-iOS#24] opened 2018-09-26 05:23 UTC
Showing All Messages
:-1: > Host: api.bugly.qq.com

:-1: > User-Agent: curl/7.54.0

:-1: > Accept: */*

:-1: > Content-Length: 332565

:-1: > Expect: 100-continue

:-1: > Content-Type: multipart/form-data; boundary=------------------------9875814cd338ebb5

:-1: > 

:-1: < HTTP/1.1 100 Continue

:-1: } [956 bytes data]

:-1: 
100  324k    0     0  100  324k      0   285k  0:00:01  0:00:01 --:--:--  285k< HTTP/1.1 200 OK

:-1: < Date: Wed, 26 Sep 2018 03:48:04 GMT

:-1: < Content-Type: application/json; charset=utf-8

:-1: < Content-Length: 89

:-1: < Connection: keep-alive

:-1: < Server: Resin/4.0.27

:-1: < Set-Cookie: JSESSIONID=c73c489f-760c-4c21-bc0e-302200f569b8; Path=/; HttpOnly

:-1: < Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Tue, 25-Sep-2018 03:48:03 GMT

:-1: < 

:-1: { [89 bytes data]

:-1: 
100  324k  100    89  100  324k     64   234k  0:00:01  0:00:01 --:--:--  234k

:-1: * Connection #0 to host api.bugly.qq.com left intact

:-1: -----------------------------

:-1: Bugly server response: {"rtcode":50500,"msg":"Success","data":{"reponseCode":"-1","reponseDesc":"system error"}}

:-1: Error: Failed to upload the zip archive file to Bugly.

:-1: --------------------------------

:-1: FAILTURE - dSYM upload complete.

:-1: --------------------------------

:-1: Failed to upload the dSYM

:-1: Please check the script and try it again.

**Comment by xy95778748** [comment] 2018-12-05 08:02
我也是。。。 感觉像是没人维护了

**Comment by signwolf** [comment] 2018-12-19 06:21
你们后来解决了吗？

**Comment by JalenChen** [comment] 2019-01-23 02:50
Duplicate of #27

**Closed by JalenChen** 2019-01-23 02:50 UTC

**Comment by signwolf** [comment] 2019-03-13 03:11
事情过去一段时间了，说一下我们解决的结果：
我们符号上传一直出现500 错误码，
最终联系到了bugly的QQ群，找到了几位非常靠谱的大咖，
后台帮我设置了一下就好了。
Q群：130979883
